[package]
name = "qrcode-generator"
version = "2.0.1"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/qrcode-generator"
homepage = "https://magiclen.org/qrcode-generator"
keywords = ["qrcode", "generate", "png", "svg", "vec"]
categories = ["encoding"]
description= "Generate QR Code matrices and images in RAW, PNG and SVG formats."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/qrcode-generator", branch = "master" }
appveyor = { repository = "magiclen/qrcode-generator", branch = "master", service = "github" }

[dependencies]
qrcodegen = { git = "https://github.com/magiclen/QR-Code-generator", branch = "master" }
image = "0.20.0"
htmlescape = "0.3.1"
rc-writer = "1.1.0"
validators = { version = "0.10", optional = true }

[features]
validator = ["validators"]

[package.metadata.docs.rs]
all-features = true