[package]
name = "qrcode-generator"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"

[dependencies]
qrcodegen = "1.3.1"
image = "0.20.0"
htmlescape = "0.3.1"
rc-writer = "1.1.0"
validators = { version = "0.10", optional = true }

[features]
validator = ["validators"]

[package.metadata.docs.rs]
all-features = true