[package]
name = "qrcode-generator"
version = "2.3.4"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/qrcode-generator"
homepage = "https://magiclen.org/qrcode-generator"
keywords = ["qrcode", "generate", "png", "svg", "vec"]
categories = ["encoding", "multimedia::images"]
description= "Generate QR Code matrices and images in RAW, PNG and SVG formats."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/qrcode-generator"
branch = "master"

[dependencies]
qrcodegen = { git = "https://github.com/magiclen/QR-Code-generator", branch = "master" }
image = "0.20.0"
htmlescape = "0.3.1"
rc-writer = "1.1.0"
percent-encoding = { version = "1.0.1", optional = true }
idna = { version = "0.1.5", optional = true }
validators = { version = ">=0.19,<0.21", optional = true }

[features]
validator = ["validators", "idna", "percent-encoding"]

[package.metadata.docs.rs]
all-features = true